version: "3.1"
services:
  www:
    build: ./php
    container_name: www_proj
    ports:
    - "8081:80"
    volumes:
      - ./www/proj:/var/www/html/
      - ./config.php:/var/www/config.php
    links:
      - db
    networks:
      - default

  db:
    image: mysql:5.5
    container_name: db_mysql_proj
    restart: always
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - default
